const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const { MongoMemoryServer } = require(path.join(process.env.STUDY_BIRDS_TEST_TOOLS, 'node_modules/mongodb-memory-server-core'));
test('assignment permissions, eligibility, version conflicts, audit and student visibility', async () => {
 process.env.JWT_SECRET = 'assignment-test-only'; let mongo, server;
 try {
  mongo = await MongoMemoryServer.create({instance:{ip:'127.0.0.1'}}); await mongoose.connect(mongo.getUri());
  const User = require('../src/models/User'); const Application = require('../src/models/Application');
  const student = await User.create({name:'Student',email:'student@test.example',role:'student'});
  const other = await User.create({name:'Other',email:'other@test.example',role:'student'});
  const staff = await User.create({name:'Advisor',email:'staff@test.example',role:'employee',permissions:['applications']});
  const finance = await User.create({name:'Finance',email:'finance@test.example',role:'employee',permissions:['student-financials']});
  const disabled = await User.create({name:'Disabled',email:'disabled@test.example',role:'employee',permissions:['applications'],isActive:false});
  const app = await Application.create({student:student._id,program:new mongoose.Types.ObjectId(),university:new mongoose.Types.ObjectId()});
  server = await new Promise(resolve => { const s=require('../src/app').listen(0,'127.0.0.1',()=>resolve(s)); });
  async function call(method, route, user, body, expected=200) {
   const result=await fetch(`http://127.0.0.1:${server.address().port}/api${route}`, {method,headers:{'Content-Type':'application/json',...(user?{Authorization:`Bearer ${jwt.sign({userId:user._id},process.env.JWT_SECRET)}`}:{})},body:body?JSON.stringify(body):undefined});
   const data=await result.json(); assert.equal(result.status,expected,JSON.stringify(data)); return data;
  }
  const route=`/applications/${app._id}/assignment`;
  await call('GET',route,null,null,401); await call('GET',route,student,null,403); await call('GET',route,finance,null,403);
  const options=await call('GET',route,staff); assert.deepEqual(options.advisors.map(x=>x.name),['Advisor']); assert.equal(options.advisors[0].email,undefined);
  const body={advisorId:String(staff._id),dueAt:'2020-01-01T12:00:00Z',version:0};
  await call('PATCH',route,student,body,403);
  await call('PATCH',route,staff,{...body,advisorId:String(disabled._id)},400);
  await call('PATCH',route,staff,{...body,advisorId:String(finance._id)},400);
  await call('PATCH',route,staff,{...body,dueAt:'invalid'},400);
  await call('PATCH',route,staff,body); await call('PATCH',route,staff,body,409);
  let saved=await Application.findById(app._id); assert.equal(saved.assignmentHistory.length,1); assert.equal(String(saved.assignmentHistory[0].changedBy),String(staff._id)); assert.equal(saved.status,'submitted');
  const overview=await call('GET','/students/overview',student); assert.equal(overview.journeys[0].followUp.advisor.name,'Advisor'); assert.equal(overview.journeys[0].followUp.overdue,true);
  assert.deepEqual((await call('GET','/students/overview',other)).journeys,[]);
  const { sendFollowUpReminders, startFollowUpReminderScheduler } = require('../src/utils/followUpReminders');
  const Notification = require('../src/models/Notification');
  await Promise.all([sendFollowUpReminders(),sendFollowUpReminders()]);
  assert.equal(await Notification.countDocuments({user:staff._id,reminderApplication:app._id}),1);
  const reminders=await call('GET','/applications/follow-up-reminders',staff);
  assert.equal(reminders.length,1);
  await call('GET','/applications/follow-up-reminders',student,null,403);
  await call('GET','/applications/follow-up-reminders',finance,null,403);
  const colleague=await User.create({name:'Colleague',email:'colleague@test.example',role:'employee',permissions:['applications']});
  assert.deepEqual(await call('GET','/applications/follow-up-reminders',colleague),[]);
  await call('PATCH',`/applications/follow-up-reminders/${reminders[0]._id}/read`,colleague,{},404);
  await call('PATCH',`/applications/follow-up-reminders/${reminders[0]._id}/read`,staff,{});
  await sendFollowUpReminders();
  assert.equal((await Notification.findById(reminders[0]._id)).isRead,true);
  assert.equal(await Notification.countDocuments({reminderApplication:app._id}),1);
  await Application.updateOne({_id:app._id},{$set:{followUpDueAt:new Date('2999-01-01')}});
  assert.deepEqual(await call('GET','/applications/follow-up-reminders',staff),[]);
  await sendFollowUpReminders(); assert.equal(await Notification.countDocuments({reminderApplication:app._id}),1);
  await Application.updateOne({_id:app._id},{$set:{followUpDueAt:new Date('2021-01-01')}});
  await User.updateOne({_id:staff._id},{$set:{isActive:false}});
  await sendFollowUpReminders(); assert.equal(await Notification.countDocuments({reminderApplication:app._id}),1);
  await User.updateOne({_id:staff._id},{$set:{isActive:true}});
  await sendFollowUpReminders(); assert.equal(await Notification.countDocuments({reminderApplication:app._id}),2);
  assert.equal((await call('GET','/applications/follow-up-reminders',staff)).length,1);
  let ran=false; const stop=startFollowUpReminderScheduler({enabled:false,run:async()=>{ran=true;}});stop();assert.equal(ran,false);
  assert.throws(()=>startFollowUpReminderScheduler({enabled:true,intervalMs:10}));
  await call('PATCH',route,staff,{advisorId:null,dueAt:null,version:1});
  await sendFollowUpReminders(); assert.deepEqual(await call('GET','/applications/follow-up-reminders',staff),[]);
  saved=await Application.findById(app._id); assert.equal(saved.assignedAdvisor,null); assert.equal(saved.assignmentHistory.length,2);
  const requeueRoute=`${route}/requeue`;
  const view=await call('GET',route,staff); assert.equal(view.application.hasAssignmentHistory,true); assert.equal(view.application.autoAssignmentEligible,false);
  await call('POST',requeueRoute,student,{version:saved.__v},403);
  await call('POST',requeueRoute,staff,{version:saved.__v+1},409);
  await call('POST',requeueRoute,staff,{version:saved.__v});
  await call('POST',requeueRoute,staff,{version:saved.__v+1},409);
  saved=await Application.findById(app._id);
  assert.equal(saved.autoAssignmentEligible,true); assert.equal(saved.assignmentHistory.length,3);
  assert.equal(saved.assignmentHistory[2].source,'requeued'); assert.equal(String(saved.assignmentHistory[2].changedBy),String(staff._id));
  assert.equal((await call('GET',route,staff)).application.autoAssignmentEligible,true);
  await Application.updateOne({_id:app._id},{$set:{status:'rejected'}});
  await call('POST',requeueRoute,staff,{version:saved.__v},409);
  await call('PATCH',route,staff,{...body,version:2},409);
  await Application.updateOne({_id:app._id},{$set:{assignedAdvisor:staff._id,followUpDueAt:new Date('2022-01-01')}});
  await sendFollowUpReminders();assert.equal(await Notification.countDocuments({reminderApplication:app._id}),2);
  assert.deepEqual(await call('GET','/applications/follow-up-reminders',staff),[]);
 } finally { if(server) await new Promise(resolve=>server.close(resolve)); await mongoose.disconnect(); if(mongo) await mongo.stop(); }
});
