const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const { MongoMemoryReplSet } = require(path.join(process.env.STUDY_BIRDS_TEST_TOOLS, 'node_modules/mongodb-memory-server-core'));

test('consultations enforce authorization, atomic reservations, safe rescheduling and deduplicated reminders', async () => {
  process.env.JWT_SECRET = 'consultation-isolated-test';
  const mongo = await MongoMemoryReplSet.create({ replSet: { count: 1, storageEngine: 'wiredTiger', ip: '127.0.0.1' } });
  let server;
  try {
    await mongoose.connect(mongo.getUri());
    const User = require('../src/models/User');
    const Notification = require('../src/models/Notification');
    const { Slot, Booking } = require('../src/models/Consultation');
    await Promise.all([User.init(), Notification.init(), Slot.init(), Booking.init()]);
    const make = (name, role = 'student', permissions = []) => User.create({ name, email: `${name}@example.test`, role, permissions });
    const student = await make('student'), other = await make('other'), stranger = await make('stranger');
    const admin = await make('admin', 'admin'), staff = await make('staff', 'employee', ['consultations']);
    const second = await make('second', 'employee', ['consultations']), finance = await make('finance', 'employee', ['student-financials']);
    server = await new Promise(resolve => { const s = require('../src/app').listen(0, '127.0.0.1', () => resolve(s)); });
    async function call(method, route, user, body, expected = 200) {
      const res = await fetch(`http://127.0.0.1:${server.address().port}/api/consultations${route}`, { method, headers: { 'Content-Type': 'application/json', ...(user ? { Authorization: `Bearer ${jwt.sign({ userId: user._id }, process.env.JWT_SECRET)}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
      const data = await res.json(); if (expected !== null) assert.equal(res.status, expected, JSON.stringify(data));
      return expected === null ? { status: res.status, data } : data;
    }
    const start = Math.ceil((Date.now() + 600000) / 1800000) * 1800000;
    const form = { advisorId: String(staff._id), startsAt: new Date(start).toISOString(), mode: 'online', meetingUrl: 'https://meet.example.test/private' };
    await call('GET', '/slots', null, null, 401);
    await call('GET', '/staff/slots', student, null, 403);
    await call('GET', '/staff/bookings', finance, null, 403);
    await call('POST', '/staff/slots', second, form, 403);
    for (const bad of [{ startsAt: new Date(start + 1000).toISOString() }, { startsAt: '2000-01-01' }, { meetingUrl: 'javascript:alert(1)' }, { mode: 'office', instructions: '' }, { advisorId: String(finance._id) }]) await call('POST', '/staff/slots', admin, { ...form, ...bad }, 400);
    const first = await call('POST', '/staff/slots', staff, form, 201);
    await call('POST', '/staff/slots', admin, form, 409);
    const parallel = await call('POST', '/staff/slots', admin, { ...form, advisorId: String(second._id) }, 201);
    const replacement = await call('POST', '/staff/slots', staff, { ...form, startsAt: new Date(start + 1800000).toISOString() }, 201);
    assert.equal((await call('GET', '/staff/slots', second)).length, 1);
    const available = await call('GET', '/slots', student);
    assert.equal(available.length, 3); assert.ok(available.every(s => !('meetingUrl' in s) && !('instructions' in s)));
    const results = await Promise.all([student, other].map(u => call('POST', '/bookings', u, { slotId: first._id }, null)));
    assert.deepEqual(results.map(r => r.status).sort(), [201, 409], JSON.stringify(results));
    const winner = results[0].status === 201 ? student : other, loser = winner === student ? other : student;
    let booking = results.find(r => r.status === 201).data;
    assert.equal(await Booking.countDocuments({ status: 'booked', slot: first._id }), 1);
    await call('POST', '/bookings', winner, { slotId: parallel._id }, 409);
    assert.equal((await Slot.findById(parallel._id)).reservation, null, 'failed double booking rolls back slot claim');
    assert.equal((await call('GET', '/mine', loser)).length, 0);
    assert.equal((await call('GET', '/mine', winner))[0].slot.meetingUrl, form.meetingUrl);
    const { sendConsultationReminders } = require('../src/utils/consultationReminders');
    assert.equal((await sendConsultationReminders(new Date(start - 1000))).sent, 1, 'first booking without remindedFor receives reminder');
    await call('POST', `/bookings/${booking._id}/cancel`, loser, { version: 0 }, 404);
    await call('POST', `/bookings/${booking._id}/cancel`, finance, { version: 0 }, 403);
    await call('POST', `/bookings/${booking._id}/cancel`, second, { version: 0 }, 404);
    await call('POST', `/bookings/${booking._id}/reschedule`, loser, { slotId: replacement._id, version: 0 }, 404);
    await call('PATCH', `/staff/slots/${first._id}`, staff, { enabled: false, version: 1 }, 409);
    const occupied = await call('POST', '/bookings', loser, { slotId: replacement._id }, 201);
    await call('POST', `/bookings/${booking._id}/reschedule`, winner, { slotId: replacement._id, version: 0 }, 409);
    assert.equal(String((await Booking.findById(booking._id)).slot), first._id);
    assert.equal(String((await Slot.findById(first._id)).reservation), booking._id);
    await call('POST', `/bookings/${occupied._id}/cancel`, loser, { version: 0 });
    booking = await call('POST', `/bookings/${booking._id}/reschedule`, winner, { slotId: replacement._id, version: 0 });
    assert.equal(booking.__v, 1); assert.equal(booking.slot, replacement._id); assert.equal(booking.history.length, 2);
    assert.equal((await Slot.findById(first._id)).reservation, null);
    await call('POST', `/bookings/${booking._id}/cancel`, winner, { version: 0 }, 409);
    const before = await Notification.countDocuments();
    const reminders = await Promise.all([sendConsultationReminders(new Date(start)), sendConsultationReminders(new Date(start))]);
    assert.equal(reminders.reduce((sum, r) => sum + r.sent, 0), 1);
    assert.equal(await Notification.countDocuments(), before + 2);
    assert.equal((await sendConsultationReminders(new Date(start))).sent, 0);
    const cancelled = await call('POST', `/bookings/${booking._id}/cancel`, staff, { version: 1 });
    assert.equal(cancelled.status, 'cancelled');
    assert.equal((await call('GET', '/mine', winner))[0].slot.meetingUrl, '');
    assert.equal((await sendConsultationReminders(new Date(start))).sent, 0);
    const replacementRow = await Slot.findById(replacement._id);
    await call('PATCH', `/staff/slots/${replacement._id}`, staff, { enabled: false, version: replacementRow.__v });
    await call('POST', '/bookings', stranger, { slotId: replacement._id }, 409);
    const transferred = await call('POST', '/bookings', stranger, { slotId: first._id }, 201);
    const notificationCount = await Notification.countDocuments();
    await call('POST', `/bookings/${transferred._id}/reschedule`, stranger, { slotId: parallel._id, version: 0 });
    assert.equal(await Notification.countDocuments(), notificationCount + 3, 'old advisor also receives the released-slot notice');
    await call('POST', `/bookings/${transferred._id}/cancel`, staff, { version: 1 }, 404);
    await call('POST', `/bookings/${transferred._id}/cancel`, second, { version: 1 });
    await User.updateOne({ _id: second._id }, { $set: { isActive: false } });
    await call('POST', '/bookings', stranger, { slotId: parallel._id }, 409);
    assert.equal((await Slot.findById(parallel._id)).reservation, null);
    // Results are only recorded after an appointment ends, by its consultant
    // or an admin, and are explicitly shared with the booked student.
    await User.updateOne({ _id: second._id }, { $set: { isActive: true } });
    const past = await Slot.create({ advisor: staff._id, startsAt: new Date(start - 86400000), mode: 'office', instructions: 'Office' });
    const finished = await Booking.create({ student: student._id, advisor: staff._id, slot: past._id, startsAt: past.startsAt });
    await Slot.updateOne({ _id: past._id }, { reservation: finished._id });
    const outcomePath = `/staff/bookings/${finished._id}/outcome`;
    const outcome = { version: 0, result: 'completed', summary: 'Reviewed program choices', nextSteps: 'Upload transcript' };
    await call('PUT', outcomePath, student, outcome, 403);
    await call('PUT', outcomePath, finance, outcome, 403);
    await call('PUT', outcomePath, second, outcome, 404);
    for (const invalid of [{ result: 'cancelled' }, { summary: ' ' }, { summary: 'x'.repeat(2001) }, { nextSteps: [] }, { version: -1 }]) {
      await call('PUT', outcomePath, staff, { ...outcome, ...invalid }, 400);
    }
    await call('PUT', `/staff/bookings/${booking._id}/outcome`, staff, { ...outcome, version: cancelled.__v }, 409);
    const futureSlot = await Slot.create({ advisor: staff._id, startsAt: new Date(start + 7200000), mode: 'office' });
    const futureBooking = await Booking.create({ student: student._id, advisor: staff._id, slot: futureSlot._id, startsAt: futureSlot.startsAt });
    await call('PUT', `/staff/bookings/${futureBooking._id}/outcome`, staff, outcome, 409);
    const beforeOutcome = await Notification.countDocuments();
    const saved = await call('PUT', outcomePath, staff, outcome);
    assert.equal(saved.status, 'completed');
    assert.equal(saved.__v, 1);
    assert.equal(saved.outcome.summary, outcome.summary);
    assert.equal(saved.outcome.recordedBy, String(staff._id));
    assert.equal(await Notification.countDocuments(), beforeOutcome + 1);
    await call('PUT', outcomePath, staff, outcome, 409);
    assert.equal(await Notification.countDocuments(), beforeOutcome + 1, 'conflicts do not notify');
    const revised = await call('PUT', outcomePath, admin, { ...outcome, version: 1, result: 'no-show', summary: 'Student did not attend' });
    assert.equal(revised.status, 'no-show');
    assert.equal(revised.outcomeHistory.length, 2);
    assert.equal(revised.outcomeHistory[0].summary, outcome.summary);
    const studentResult = (await call('GET', '/mine', student)).find(b => b._id === String(finished._id));
    assert.equal(studentResult.outcome.summary, 'Student did not attend');
    assert.ok(!(await call('GET', '/mine', stranger)).some(b => b._id === String(finished._id)));
    assert.ok(!(await call('GET', '/staff/bookings', second)).some(b => b._id === String(finished._id)));
    const dates = [2, 9, 16].map(days => new Date(start + days * 86400000).toISOString());
    const batch = { ...form, startsAt: dates };
    await call('POST', '/staff/slots/batch', student, batch, 403);
    await call('POST', '/staff/slots/batch', second, batch, 403);
    for (const badDates of [[], Array(13).fill(dates[0]), [dates[0], dates[0]], ['invalid'], [new Date(start + 100 * 86400000).toISOString()]]) {
      await call('POST', '/staff/slots/batch', staff, { ...batch, startsAt: badDates }, 400);
    }
    const series = await call('POST', '/staff/slots/batch', staff, batch, 201);
    assert.equal(series.length, 3);
    const unclaimedDate = new Date(start + 3 * 86400000).toISOString();
    await call('POST', '/staff/slots/batch', staff, { ...batch, startsAt: [unclaimedDate, dates[1]] }, 409);
    assert.equal(await Slot.countDocuments({ advisor: staff._id, startsAt: new Date(unclaimedDate) }), 0, 'conflicting batch rolls back every inserted slot');
    assert.equal(await Slot.countDocuments({ _id: { $in: series.map(s => s._id) } }), 3);
    const parallelBatch = { ...batch, startsAt: [unclaimedDate, new Date(start + 10 * 86400000).toISOString()] };
    const batchResults = await Promise.all([1, 2].map(() => call('POST', '/staff/slots/batch', staff, parallelBatch, null)));
    assert.deepEqual(batchResults.map(r => r.status).sort(), [201, 409]);
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    await mongoose.disconnect(); await mongo.stop();
  }
});
