const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const mongoose = require('mongoose');
const { MongoMemoryServer } = require(path.join(process.env.STUDY_BIRDS_TEST_TOOLS, 'node_modules/mongodb-memory-server-core'));

test('application requirements, document ownership, and dashboard isolation', async () => {
  process.env.JWT_SECRET = 'isolated-student-workflow-test-key';
  let mongo, server;
  try {
    mongo = await MongoMemoryServer.create({ instance: { ip: '127.0.0.1' } });
    await mongoose.connect(mongo.getUri());
    const app = require('../src/app');
    const User = require('../src/models/User');
    const Program = require('../src/models/Program');
    const Document = require('../src/models/Document');
    const Invoice = require('../src/models/Invoice');
    const Notification = require('../src/models/Notification');
    const Application = require('../src/models/Application');
    const Country = require('../src/models/Country');
    const University = require('../src/models/University');
    server = await new Promise(resolve => { const s = app.listen(0, '127.0.0.1', () => resolve(s)); });
    const origin = `http://127.0.0.1:${server.address().port}/api`;
    async function call(method, route, token, body, expected = 200) {
      const response = await fetch(origin + route, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
      const result = await response.json();
      assert.equal(response.status, expected, `${route}: ${JSON.stringify(result)}`);
      return result;
    }
    const a = await call('POST', '/auth/register', null, { name: 'A', email: 'a@example.test', password: 'Password123!' }, 201);
    const b = await call('POST', '/auth/register', null, { name: 'B', email: 'b@example.test', password: 'Password123!' }, 201);
    const country = await Country.create({ name: 'Test country', code: 'ZZ' });
    const university = await University.create({ name: 'Test university', country: country._id });
    const program = await Program.create({ title: 'Test degree', degreeLevel: 'Bachelor', fieldOfStudy: 'Engineering', university: university._id, requiredDocumentTypes: ['transcript'] });
    const doc = await Document.create({ student: a.user._id, type: 'transcript', fileName: 'test.pdf', filePath: 'https://example.test/test.pdf' });
    const foreign = await Document.create({ student: b.user._id, type: 'transcript', fileName: 'other.pdf', filePath: 'https://example.test/other.pdf' });
    const missing = await call('POST', '/applications', a.token, { programId: program._id, documentIds: [] }, 400);
    assert.deepEqual(missing.missingDocumentTypes, ['transcript']);
    await call('POST', '/applications', a.token, { programId: program._id, documentIds: [foreign._id] }, 400);
    await call('POST', '/applications', a.token, { programId: program._id, documentIds: [doc._id, doc._id] }, 400);
    const created = await call('POST', '/applications', a.token, { programId: program._id, documentIds: [doc._id] }, 201);
    assert.deepEqual(created.requiredDocumentTypes, ['transcript']);
    await call('POST', '/applications', a.token, { programId: program._id, documentIds: [doc._id] }, 400);
    assert.equal(await Application.countDocuments(), 1);
    await User.create({ name: 'Admin', email: 'admin@example.test', password: 'Password123!', role: 'admin' });
    const admin = await call('POST', '/auth/login', null, { email: 'admin@example.test', password: 'Password123!' });
    await call('PUT', `/programs/${program._id}`, a.token, { requiredDocumentTypes: [] }, 403);
    await call('PUT', `/programs/${program._id}`, admin.token, { requiredDocumentTypes: ['transcript', 'transcript'] }, 400);
    await call('PUT', `/programs/${program._id}`, admin.token, { requiredDocumentTypes: [] });
    assert.deepEqual((await call('GET', `/programs/${program._id}`)).requiredDocumentTypes, []);
    assert.deepEqual((await Application.findById(created._id)).requiredDocumentTypes.toObject(), ['transcript']);

    await Invoice.create({ student: b.user._id, invoiceNumber: 'foreign', description: 'Private B invoice', amount: 500, dueDate: '2020-01-01' });
    await Invoice.create({ student: a.user._id, invoiceNumber: 'own', description: 'A invoice', amount: 100, status: 'pending-confirmation' });
    await Notification.insertMany(Array.from({ length: 8 }, (_, index) => ({ user: a.user._id, title: `Notice ${index}`, message: 'Test', isRead: false })));
    const overview = await call('GET', '/students/overview', a.token);
    assert.equal(overview.nextAction.code, 'payment-review');
    assert.equal(overview.stats.pendingPayments, 0);
    assert.equal(overview.stats.unreadNotifications, 9);
    assert.ok(!JSON.stringify(overview).includes('Private B invoice'));
    assert.equal((await call('GET', '/students/overview', b.token)).stats.pendingPayments, 1);
    await call('GET', '/students/overview', null, null, 401);
    const saved = await Application.findById(created._id);
    saved.status = 'rejected'; await saved.save();
    assert.equal((await Application.findById(created._id)).detailedStatus, 'rejected');
    saved.detailedStatus = 'conditional-admission'; await saved.save();
    assert.equal((await Application.findById(created._id)).status, 'under-review');
    doc.status = 'verified'; await doc.save();
    assert.equal((await Document.findById(doc._id)).detailedStatus, 'approved');
    doc.detailedStatus = 'needs-revision'; await doc.save();
    assert.equal((await Document.findById(doc._id)).status, 'pending');
    const replacement = await Document.create({ student: a.user._id, type: 'transcript', fileName: 'new.pdf', filePath: 'https://example.test/new.pdf' });
    const route = `/applications/${created._id}/documents`;
    let current = await Application.findById(created._id);
    await call('PATCH', route, a.token, { documentId: replacement._id, version: current.__v }, 409);
    current.detailedStatus = 'documents-missing'; await current.save();
    await call('PATCH', route, b.token, { documentId: foreign._id, version: current.__v }, 404);
    await call('PATCH', route, a.token, { documentId: foreign._id, version: current.__v }, 404);
    await call('PATCH', route, a.token, { documentId: doc._id, version: current.__v }, 400);
    const request = () => fetch(origin + route, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${a.token}` }, body: JSON.stringify({documentId: replacement._id, version: current.__v}) });
    const concurrent = await Promise.all([request(), request()]);
    assert.deepEqual(concurrent.map(response => response.status).sort(), [200, 409]);
    current = await Application.findById(created._id);
    assert.equal(current.documentRevisions.length, 1);
    assert.equal(String(current.documentRevisions[0].previousDocuments[0]), String(doc._id));
    assert.deepEqual(current.documents.map(String), [String(replacement._id)]);
    assert.equal(current.detailedStatus, 'documents-missing');
    assert.ok(await Document.findById(doc._id));
    await call('PATCH', route, a.token, { documentId: replacement._id, version: current.__v }, 409);
    await Invoice.updateMany({ student: a.user._id }, { status: 'paid' });
    assert.equal((await call('GET', '/students/overview', a.token)).nextAction.code, 'document-review');
    const requestsRoute = `/applications/${created._id}/document-requests`;
    current = await Application.findById(created._id);
    await call('POST', requestsRoute, a.token, { type: 'language-certificate', note: 'Provide language result', version: current.__v }, 403);
    await call('POST', requestsRoute, admin.token, { type: 'invalid', note: 'Test', version: current.__v }, 400);
    let requested = await call('POST', requestsRoute, admin.token, { type: 'language-certificate', note: 'Provide language result', version: current.__v }, 201);
    const requestId = requested.documentRequests[0]._id;
    await call('POST', requestsRoute, admin.token, { type: 'language-certificate', note: 'Duplicate', version: requested.__v }, 409);
    assert.equal((await call('GET', '/students/overview', a.token)).nextAction.code, 'additional-document-request');
    await call('PATCH', `${requestsRoute}/${requestId}`, admin.token, { decision: 'approved', note: 'No upload yet', version: requested.__v }, 409);
    const languageDoc = await Document.create({ student: a.user._id, type: 'language-certificate', fileName: 'language.pdf', filePath: 'https://example.test/language.pdf' });
    let submitted = await call('PATCH', route, a.token, { documentId: languageDoc._id, version: requested.__v });
    assert.equal(submitted.documentRequests[0].status, 'submitted');
    assert.equal(submitted.documentRequests[0].document, String(languageDoc._id));
    assert.equal((await call('GET', '/students/overview', a.token)).nextAction.code, 'additional-document-review');
    await call('PATCH', `${requestsRoute}/${requestId}`, a.token, { decision: 'approved', note: 'Student self approval', version: submitted.__v }, 403);
    requested = await call('PATCH', `${requestsRoute}/${requestId}`, admin.token, { decision: 'requested', note: 'Upload a clearer scan', version: submitted.__v });
    const clearer = await Document.create({ student: a.user._id, type: 'language-certificate', fileName: 'clearer.pdf', filePath: 'https://example.test/clearer.pdf' });
    submitted = await call('PATCH', route, a.token, { documentId: clearer._id, version: requested.__v });
    clearer.detailedStatus = 'rejected'; await clearer.save();
    await call('PATCH', `${requestsRoute}/${requestId}`, admin.token, { decision: 'approved', note: 'Cannot accept rejected document', version: submitted.__v }, 409);
    clearer.detailedStatus = 'uploaded'; await clearer.save();
    const approved = await call('PATCH', `${requestsRoute}/${requestId}`, admin.token, { decision: 'approved', note: 'Requirement fulfilled', version: submitted.__v });
    assert.equal(approved.documentRequests[0].status, 'approved');
    assert.equal(approved.documentRequests[0].reviewedBy, admin.user._id);
    assert.equal(approved.detailedStatus, 'documents-missing');
    await call('PATCH', `${requestsRoute}/${requestId}`, admin.token, { decision: 'requested', note: 'Cannot reopen closed request', version: approved.__v }, 409);
    const otherRequest = await call('POST', requestsRoute, admin.token, { type: 'other', note: 'Optional supporting evidence', version: approved.__v }, 201);
    const otherId = otherRequest.documentRequests.find(item => item.type === 'other')._id;
    const cancelled = await call('PATCH', `${requestsRoute}/${otherId}`, admin.token, { decision: 'cancelled', note: 'No longer required', version: otherRequest.__v });
    assert.equal(cancelled.documentRequests.find(item => item._id === otherId).status, 'cancelled');
    assert.notEqual((await call('GET', '/students/overview', a.token)).nextAction.code, 'additional-document-request');
    assert.equal(await User.countDocuments(), 3);
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    await mongoose.disconnect(); if (mongo) await mongo.stop();
  }
});
